### PR TITLE
Flat anonymous  struct field

### PR DESCRIPTION
**Pull request by micln**
**What this PR does**:

- flat anonymons fields
- ignore field with tag `hessian:"-"`

#153 

**Special notes for your reviewer**:

when find a anonymous field in scanning struct's fields, encoding/json will flat field immediately. but I put the field to queue and flat latter

**Does this PR introduce a user-facing change?**:

```release-note
result of encode(object) has changed,
but the method decode is compatibility with previous version
```

### CODE REVIEW

**Comment by micln** [comment]
need merge #150 first

**Comment by wongoo** [comment]
I will review this PR after https://github.com/apache/dubbo-go-hessian2/pull/150 being merged.

**Comment by fangyincheng** [comment]
Pls resolve conflicts @micln

**Comment by micln** [comment]
should we support embed pointer like

```go
type Dog struct{
    *Aninal
}
```

**Comment by micln** [comment]
@fangyincheng @wanghbxxxx @aliiohs pls review this agian, thanks

**Comment by wongoo** [comment]
> should we support embed pointer like
> 
> ```go
> type Dog struct{
>     *Aninal
> }
> ```
> 
> The super class in java will not be null, so the protocal don't need handle it. That means we can't marshal the ptr to a nil (and new a instance to hold feilds).
> 
> So I think we don't need to support the embed pointer today.

agree

**Comment by aliiohs** [comment]
LGTM

**Comment by AlexStocks** [comment]
@micln pls update the readme. add some explanation about java&go inheritance, and the anonymous struct field.

**Comment by wongoo** [comment]
@micln  pls push a new PR if need update readme or demo

**Pull request merged**
