### PR TITLE
if map is pojo, write class name first

### PR DESCRIPTION
**Pull request by zhengzepeng**
**What this PR does**:

if map is pojo, write class name first

**Which issue(s) this PR fixes**:

#319 

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Review by AlexStocks — APPROVED** [review]

**Comment by AlexStocks** [comment]
@zhengzepeng pls add an ut for this pr.

**Comment by zhengzepeng** [comment]
> @zhengzepeng pls add an ut for this pr.

ok

**Review by wongoo — APPROVED** [review]
LGTM

**Comment by AlexStocks** [comment]
@zhengzepeng I have merged your pr. pls upgrade the hessian-go version in dubbo-go and dubbo-go-samples.

**Pull request merged**
