### PR TITLE
Ftr: create instance by java name

### PR DESCRIPTION
**Pull request by Patrick0308**
**What this PR does**:
create instance by javaName

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by wongoo** [comment]
@Patrick0308  when will this needed, can you give some examples？ Thanks！

**Comment by Patrick0308** [comment]
@wongoo I use  `CreateInstanceByJavaName` to create instance when `Dubbogo Provider` receive the request of generic invoke. In generic invoke, the arguments's type is `map`. I need to convert `map` to `struct`. 
Take one simple example:
``` go
func (ef *GenericServiceFilter) Invoke(invoker protocol.Invoker, invocation protocol.Invocation) protocol.Result {
		parameterTypes := oldArguments[1].([]string)
		oldParams := oldArguments[2].([]interface{})
                javaName := parameterTypes[0]
		instance := hessian.CreateInstanceByJavaName(javaName)
		if instance != nil{
                        // convert map to struct
			newParam = mapstructure.Decode(oldParams[i],instance)
                 }
                // DO SOMETHING
                return invoker.Invoke(newInvocation)
}
```

**Comment by wongoo** [comment]
LGTM

**Comment by Patrick0308** [comment]
@fangyincheng @wongoo I found another better way to resolve my problem. Do you think  this pr need be merged?

**Comment by wongoo** [comment]
@Patrick0308 not need to merge this pr if not useful.

**Pull request closed without merging**
