### PR TITLE
Fix: decType

### PR DESCRIPTION
**Pull request by fangyincheng**
**What this PR does**:

`tag` is already read, it should not to read in the `decInt32` again.

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

### CODE REVIEW

**Comment by wongoo** [comment]
LGTM

**Comment by wongoo** [comment]
@fangyincheng this issue happens when ref exist struct type , which is not covered by unit test. So appreciate If u can add a unit for it.

**Comment by AlexStocks** [comment]
@fangyincheng  a ut pls.

**Comment by fangyincheng** [comment]
> @fangyincheng this issue happens when ref exist struct type , which is not covered by unit test. So appreciate If u can add a unit for it.

Can ut start in `https://github.com/apache/dubbo-go-hessian2/issues/119`.

**Comment by wongoo** [comment]
> 
> Can ut start in `https://github.com/apache/dubbo-go-hessian2/issues/119`.

yes, u can submit a UT for it whenever you have time.

**Comment by wongoo** [comment]
LGTM and can be merged

**Pull request merged**
