### PR TITLE
Ftr: support encoding *int

### LINKED ISSUE #124: Add: mapping go *int to java Integer
**What would you like to be added**:
mapping go `*int` to java `Integer` 
- codec support between java `Integer` null and go `*int` nil

**Why is this needed**:
- `Integer` is used widely in java

### PR DESCRIPTION
**Pull request by Patrick0308**
**What this PR does**:
  *int to java int
**Which issue(s) this PR fixes**:

Fixes #124 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by wongoo** [comment]
@Patrick0308 thanks for contribution, the unit test failed for `reflect: call of reflect.Value.IsNil on int32 Value`, pls fix it.

**Comment by wongoo** [comment]
this PR is mapping java Integer to golang int32, should we mapping it to golang int instead?  
What's your opinion?  @AlexStocks  @fangyincheng  @aliiohs @pantianying 

see: https://github.com/hessian-group/hessian-type-mapping

**Comment by Patrick0308** [comment]
@wongoo I fixed it, pls check again.

**Comment by wongoo** [comment]
LGTM

**Pull request merged**
