### PR TITLE
update gost v1.5.1 bytes pool

### PR DESCRIPTION
**Pull request by micln**
**What this PR does**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by wongoo** [comment]
LGTM

**Comment by micln** [comment]
- [ ] todo: fix bytes ptr

**Comment by AlexStocks** [comment]
LGTM.

**Comment by AlexStocks** [comment]
@wongoo i think u can merge this pr.

**Pull request merged**
