### PR TITLE
fix duplicatedly adding list type in type map

### PR DESCRIPTION
**Pull request by wongoo**
**What this PR does**:
- fix duplicatedly adding list type in type map
- 
**Which issue(s) this PR fixes**:
None

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
```release-note
- fix duplicatedly adding list type in type map
```

### CODE REVIEW

**Comment by wongoo** [comment]
the test fail for go1.13 there is infinite loop to call reflect.deepequal , which is ok for go1.16

**Review by wenxuwan — APPROVED** [review]

**Comment by wenxuwan** [comment]
> the test fail for go1.13 there is infinite loop to call reflect.deepequal , which is ok for go1.16

I am using version 1.13 in my environment now. Will this error have any effect?

**Comment by wongoo** [comment]
> > the test fail for go1.13 there is infinite loop to call reflect.deepequal , which is ok for go1.16
> 
> I am using version 1.13 in my environment now. Will this error have any effect?

Hessian supports object loop reference， it's not the issue of hessian. 
There is infinite loop only when calling reflect.deepequal to check self reference object.

Anyway, I'll change the unit test to not use the reflect.deepequal.

**Comment by wenxuwan** [comment]
> > > the test fail for go1.13 there is infinite loop to call reflect.deepequal , which is ok for go1.16
> > 
> > 
> > I am using version 1.13 in my environment now. Will this error have any effect?
> 
> Hessian supports object loop reference， it's not the issue of hessian.
> There is infinite loop only when calling reflect.deepequal to check self reference object.
> 
> Anyway, I'll change the unit test to not use the reflect.deepequal.

got it , thanks for your response

**Review by AlexStocks — APPROVED** [review]

**Review by LaurenceLiZhixin — APPROVED** [review]

**Review by gaoxinge — APPROVED** [review]

**Comment by AlexStocks** [comment]
pls fix the ut failure.

**Review by zouyx — APPROVED** [review]

**Review by zouyx — COMMENTED** [review]
one of checking was fail....

**Comment by wongoo** [comment]
unit test already been fixed， I will merge this pr

**Pull request merged**
