### PR TITLE
[WIP] Decode Non-Exist field in Go

### LINKED ISSUE #183: javaBean返回的字段信息比struct多的时候，无法反序列化
英文不好，直接中文了

**What would you like to be added**:

golang反序列化的时候struct字段信息支持缺省字段

https://github.com/apache/dubbo-go-hessian2/blob/c4e7f352422864fb76182bfbe8adcaf298d86573/object.go#L342

**Why is this needed**:
golang hessian2反序列化如果struct字段信息比javaBean字段信息少的时候，会出现反序列化失败的错误

### PR DESCRIPTION
**Pull request by micln**
**What this PR does**:

**Which issue(s) this PR fixes**:

Fixes #183 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by AlexStocks** [comment]
pls fix the travis failure.

**Comment by wongoo** [comment]
there is no log in hessian now， it will return error if something goes wrong. should hessian support log? it may cause lower performance. If yes, I think it's should accept a logger , not calling the `log.Print`.

```go
type loggerFunc func( format string, args... interface)
func emptyLogger ( format string, args... interface) {}

var logger = emptyLogger

func EnableLogger(l loggerFunc){
      logger = l
}
func DisableLogger(){
      logger = emptyLogger
}
```

@AlexStocks @fangyincheng @hxmhlt

**Comment by AlexStocks** [comment]
@wongoo agree with u.

**Comment by micln** [comment]
this pr has some code for travis debug, I will call for review later

**Pull request closed without merging**
